### ISSUE TITLE
v0.3.1 includes `.node_modules.ember-try` folder

### ISSUE THREAD

**Issue by Turbo87** [bendemboski/ember-concurrency-test-waiter#14]
see https://unpkg.com/browse/ember-concurrency-test-waiter@0.3.1/

**Comment by ef4** [comment]
Just noticed this too. It's 106MB of unnecessary download for each user. It's simple to fix if you just publish a 0.3.2 being careful to clean that directory up first locally.

**Comment by bendemboski** [comment]
https://unpkg.com/browse/ember-concurrency-test-waiter@0.3.2/
