### ISSUE TITLE
Fails with ember-concurrency#277 and Ember canary

### ISSUE THREAD

**Issue by gitKrystan** [bendemboski/ember-concurrency-test-waiter#6]
I'm trying to get our tests passing on Ember canary and ran into the issue you described in https://github.com/machty/ember-concurrency/issues/279 (thanks for tracking that down, by the way).

I pointed our ember-try 'canary' scenario at https://github.com/machty/ember-concurrency/pull/277, but now I'm running into this assertion from `ember-concurrency-test-waiter`:

https://github.com/bendemboski/ember-concurrency-test-waiter/blob/8d302fbb24899c8ee59a05f5da485f0254e3f91f/addon/with-test-waiter.js#L12

**Comment by bendemboski** [comment]
Right, thanks for the report @gitKrystan -- that PR is definitely going to break `ember-concurrency-test-waiter` (not just the compatibility check, but the whole mechanism to install a test waiter will no longer work!). I'll work on a solution, and hopefully get [some help](https://github.com/machty/ember-concurrency/pull/277#issuecomment-463351043)!

**Comment by bendemboski** [comment]
Fixed via https://github.com/machty/ember-concurrency/pull/277
